name: Build

on:
  push:

jobs:
  electron:
    name: Desktop app (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: npm run package

      - name: Upload artifact (Portable)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-Portable
          path: release/build/win-unpacked

      - name: Upload artifact (Installer)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-Installer
          path: release\build\Chatbox-*-Setup.exe
